---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 14.3.0
    chart: kube-prometheus-stack
    helm:
      values: |
        defaultRules:
          create: false

        alertmanager:
          enabled: false

        grafana:
          service:
            type: NodePort
            nodePort: 30100

        prometheus:
          service:
            type: NodePort
            nodePort: 30200

        prometheusOperator:
          tlsProxy:
            enabled: false
          tls:
            enabled: true

        coreDns:
          enabled: false

        kubeEtcd:
          enabled: false

        kubeScheduler:
          enabled: false

        kubeProxy:
          enabled: false

  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
