---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cardano-node
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/puchz/cardano-node.git
    targetRevision: {{ .Values.git.targetRevision }}
    path: applications/cardano-node
    helm:
      valueFiles:
        - {{ .Values.cnode }}

  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
