{
 "title": "Monitor: Zeus node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "cardano-testnet, cardano-mainnet"
   },
   {
    "name": "pod",
    "query": "cardano-node-relay-uno-0, cardano-node-relay-dos-0, cardano-node-pool-0"
   }
  ]
 },
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Mempool bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Mempool transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "TXs processed",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_txsProcessedNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Slot in Epoch"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(pod) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / (1000)", "legendFormat": "{{namespace}}-{{pod}}" }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}[150s])*60",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{namespace}}-{{pod}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{namespace}}-{{pod}} {{device}} write"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{namespace}}-{{pod}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{namespace}}-{{pod}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Chain density %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{namespace=~\"$namespace\", pod=~\"$pod\"} * 100",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Key rotation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Current period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Expiry period"
    },
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int{namespace=\"$namespace\", pod=\"$pod\"} * 1.5)",
     "legendFormat": "Days left"
    }
   ]
  }
 ]
}