---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-2
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-3
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data3"
