---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pool-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: cardano-node
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageClaim }}
{{- range $relays := .Values.relays }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-{{ $relays.name }}-pvc
  namespace: {{ $.Values.namespace }}
  labels:
    app: cardano-node
spec:
  storageClassName: local-storage
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storageClaim }}
{{- end }}
