---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pool
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    name: {{ .Values.pool.name }}
    type: pool
    network: {{ .Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ .Values.pool.port }}
      targetPort: node
{{- range $relays := .Values.relays }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-relay-{{ $relays.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $.Release.Name }}
    name: {{ $relays.name }}
    type: relay
    network: {{ $.Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ $relays.port }}
      targetPort: node
      nodePort: {{ $relays.nodePort }}
  type: NodePort
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-relay-int
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: cardano-exporter
    app.kubernetes.io/name: prometheus-cardano-exporter
spec:
  selector:
    app: {{ .Release.Name }}
    network: {{ .Values.network }}
  ports:
    - name: prom
      protocol: TCP
      port: 12798
      targetPort: prom
    - name: prom2
      protocol: TCP
      port: 9100
      targetPort: prom2
