apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-svc-monitor
  namespace: {{ .Values.prometheusNamespace }}
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: prom
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
