{{- range $relays := .Values.relays }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "cardano-node-relay-{{ $relays.name }}"
  namespace: {{ $.Values.namespace }}
spec:
  serviceName: "cardano-node-relay-{{ $relays.name }}"
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      name: {{ $relays.name }}
      type: relay
      network: {{ $.Values.network }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        name: {{ $relays.name }}
        type: relay
        network: {{ $.Values.network }}
    spec:
      containers:
      - image: cardano-node:1.24.2
        name: {{ $.Release.Name }}
        command:
          - "cardano-node"
        args:
          - "run"
          - "--topology"
          - "/etc/config/testnet-topology.json"
          - "--database-path"
          - "/db"
          - "--socket-path"
          - "/db/node.socket"
          - "--host-addr"
          - "0.0.0.0"
          - "--port"
          - "3000"
          - "--config"
          - "/etc/config/testnet-config.json"
        ports:
          - containerPort: {{ $relays.port }}
            name: node
          - name: prom
            containerPort: {{ $relays.prometheusPort | default 12798 }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 40
        readinessProbe:
          httpGet:
            path: /metrics
            port: prom
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 40
        {{- with $.Values.resources }}
        resources:
{{ toYaml . | indent 12 }}
        {{- end }}
        volumeMounts:
          - name: config-files
            mountPath: "/etc/config/testnet-topology.json"
            subPath: "testnet-topology-relay.json"
          - name: config-files
            mountPath: "/etc/config/testnet-config.json"
            subPath: "testnet-config.json"
          - name: db
            mountPath: /db
      volumes:
        - name: config-files
          configMap:
            name: {{ $.Release.Name }}-configmap
        - name: db
          persistentVolumeClaim:
            claimName: relay-{{ $relays.name }}-pvc
{{- end }}
{{- $pool := .Values.pool }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-pool
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "{{ .Release.Name }}-pool"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      name: {{ $pool.name }}
      type: pool
      network: {{ .Values.network }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        name: {{ $pool.name }}
        type: pool
        network: {{ .Values.network }}
    spec:
      containers:
      - image: cardano-node:1.24.2
        name: {{ .Release.Name }}
        command:
          - "cardano-node"
        args:
          - "run"
          - "--topology"
          - "/etc/config/testnet-topology.json"
          - "--database-path"
          - "/db"
          - "--socket-path"
          - "/db/node.socket"
          - "--host-addr"
          - "0.0.0.0"
          - "--port"
          - "3000"
          - "--config"
          - "/etc/config/testnet-config.json"
          - "--shelley-kes-key"
          - "/etc/keys/kes.skey"
          - "--shelley-vrf-key"
          - "/etc/keys/vrf.skey"
          - "--shelley-operational-certificate"
          - "/etc/keys/node.cert"
        ports:
          - containerPort: {{ $pool.port }}
            name: node
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 40
        readinessProbe:
          httpGet:
            path: /metrics
            port: prom
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 40
        volumeMounts:
          - name: config-files
            mountPath: "/etc/config/testnet-topology.json"
            subPath: "testnet-topology-pool.json"
          - name: config-files
            mountPath: "/etc/config/testnet-config.json"
            subPath: "testnet-config.json"
          - name: secret-keys
            mountPath: /etc/keys/vrf.skey
            subPath: vrf.skey
          - name: secret-keys
            mountPath: /etc/keys/kes.skey
            subPath: kes.skey
          - name: secret-keys
            mountPath: /etc/keys/node.cert
            subPath: node.cert
          - name: db
            mountPath: /db
      volumes:
        - name: config-files
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: secret-keys
          secret:
            secretName: cardano-testnet-secrets
            defaultMode: 0400
        - name: db
          persistentVolumeClaim:
            claimName: pool-pvc
