apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-svc-monitor
  namespace: {{ .Values.namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: prom
      path: /metrics
      interval: 1m
      scrapeTimeout: 1m
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: cardano-exporter
      app.kubernetes.io/name: prometheus-cardano-exporter
