---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pool
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    name: {{ .Values.pool.name }}
    type: pool
    network: {{ .Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ .Values.pool.port }}
      targetPort: node
{{- range $relays := .Values.relays }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-relay-{{ $relays.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $.Release.Name }}
    name: {{ $relays.name }}
    type: relay
    network: {{ $.Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ $relays.port }}
      targetPort: node
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-relay-out
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    type: relay
    network: {{ .Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ .Values.relayPort }}
      targetPort: node
      nodePort: {{ .Values.nodePort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-relay-int
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    type: relay
    network: {{ .Values.network }}
  ports:
    - protocol: TCP
      name: prom
      port: {{ .Values.prometheusPort | default 12798 }}
      targetPort: prom
