{{ if .Values.topologyUpdater.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-updater
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-updater
      network: {{ $.Values.network }}
  template:
    metadata:
      labels:
        app: topology-updater
        network: {{ $.Values.network }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: topology-updater
          image: "{{ .Values.topologyUpdater.image.repository }}:{{ .Values.topologyUpdater.image.tag }}"
          command: [ "bash", "-c", "while true; do bash /opt/cardano-node/utils/topologyUpdater.sh; sleep 3600; done" ]
          env:
            - name: NETWORK
              value: {{ .Values.network }}
            - name: BASE_URL
              value: "https://api.clio.one/htopology/v1"
            - name: CNODE_HOSTNAME
              value: {{ .Values.cardanoNodeHostname }}
{{- range $relays := .Values.relays }}
            - name: {{ $relays.nametopology }}
              value: {{ $relays.nodePort | quote }}
{{- end }}
            - name: MAX_PEERS
              value: {{ .Values.topologyUpdater.maxPeers | quote }}
            - name: CNODE_TOPOLOGY
              value: /tmp/topology.json
          volumeMounts:
            - name: cardano-node-utils
              mountPath: "/opt/cardano-node/utils"
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: cardano-node-utils
          configMap:
            name: cardano-node-utils
  strategy:
    type: Recreate
{{ end }}
