---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: dnsutils
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardano-testnet
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardano-mainnet
