network: mainnet
namespace: cardano-mainnet

resources:
  limits:
    memory: "3Gi"
    cpu: 1
  requests:
    memory: "2Gi"
    cpu: 1

storageClaim: 15Gi

relays:
  - name: uno
    port: 3001
  - name: dos
    port: 3002
