network: testnet
namespace: cardano-testnet

resources:
  limits:
    memory: "3Gi"
    cpu: 1
  requests:
    memory: "2Gi"
    cpu: 1

storageClaim: 5Gi

relays:
  - name: uno
    port: 3000
  - name: dos
    port: 3000
