network: testnet
namespace: cardano-testnet
cardanoNodeHostname: zeusdotdog.duckdns.org

resources:
  limits:
    memory: "3Gi"
    cpu: 1
  requests:
    memory: "2Gi"
    cpu: 1

storageClaim: 5Gi

relays:
  - name: uno
    nametopology: CNODE_PORT_UNO
    port: 3001
    nodePort: 5000
  - name: dos
    nametopology: CNODE_PORT_DOS
    port: 3002
    nodePort: 5001
