network: testnet
namespace: cardano-testnet

resources:
  limits:
    memory: "2Gi"
    cpu: 1
  requests:
    memory: "1Gi"
    cpu: 1

storageClaim: 5Gi

relays:
  - name: uno
    port: 3001
  - name: dos
    port: 3002
