storageSize: 5Gi
prometheusPort: 12798
prometheusPort2: 9100
prometheusNamespace: monitoring

resources:
  limits:
    memory: "2Gi"
    cpu: 2
  requests:
    memory: "1Gi"
    cpu: 1

topologyUpdater:
  enabled: true
  image:
    repository: "cn-utils"
    tag: "0.1"
  maxPeers: 15
