network: testnet
namespace: cardano-testnet

resources:
  limits:
    memory: "8Gi"
    cpu: 3
  requests:
    memory: "6Gi"
    cpu: 2

storageClaim: 5Gi

relays:
  - name: uno
    port: 3000
  - name: dos
    port: 3000
